### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by woyoudianhuai** [googlesamples/android-UniversalMusicPlayer#106]
FATAL EXCEPTION: main
                                                                        Process: com.example.android.uamp, PID: 2905
                                                                        Theme: themes:{}
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.uamp/com.example.android.uamp.ui.MusicPlayerActivity}: java.lang.RuntimeException: com.google.android.gms.internal.zztl$zza: No acceptable module found. Local version is 0 and remote version is 0.
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2449)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2521)
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5477)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                         Caused by: java.lang.RuntimeException: com.google.android.gms.internal.zztl$zza: No acceptable module found. Local version is 0 and remote version is 0.
                                                                            at com.google.android.gms.internal.zzog.zzbe(Unknown Source)
                                                                            at com.google.android.gms.internal.zzog.zza(Unknown Source)
                                                                            at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source)
                                                                            at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source)
                                                                            at com.example.android.uamp.ui.ActionBarCastActivity.onCreate(ActionBarCastActivity.java:141)
                                                                            at com.example.android.uamp.ui.BaseActivity.onCreate(BaseActivity.java:49)
                                                                            at com.example.android.uamp.ui.MusicPlayerActivity.onCreate(MusicPlayerActivity.java:57)
                                                                            at android.app.Activity.performCreate(Activity.java:6285)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2521) 
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:148) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5477) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                         Caused by: com.google.android.gms.internal.zztl$zza: No acceptable module found. Local version is 0 and remote version is 0.
                                                                            at com.google.android.gms.internal.zztl.zza(Unknown Source)
                                                                            at com.google.android.gms.internal.zztl.zza(Unknown Source)
                                                                            at com.google.android.gms.internal.zzog.zzbe(Unknown Source) 
                                                                            at com.google.android.gms.internal.zzog.zza(Unknown Source) 
                                                                            at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source) 
                                                                            at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source) 
                                                                            at com.example.android.uamp.ui.ActionBarCastActivity.onCreate(ActionBarCastActivity.java:141) 
                                                                            at com.example.android.uamp.ui.BaseActivity.onCreate(BaseActivity.java:49) 
                                                                            at com.example.android.uamp.ui.MusicPlayerActivity.onCreate(MusicPlayerActivity.java:57) 
                                                                            at android.app.Activity.performCreate(Activity.java:6285) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2521) 
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:148) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5477) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by JaffarOu** [comment]
I meet this problem too,do you resolve it yet?

**Comment by JaffarOu** [comment]
I meet this problem too,do you resolve it yet?

**Comment by pingcai** [comment]
me too

**Comment by o0yangyang0o** [comment]
What is the google service package ? How to install it ?

**Comment by nic0lette** [comment]
This should have been addressed in the current version of the code, which verifies Google Play Services is installed/up to date before attempting to setup for Cast.
