### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by dragonxking** [googlesamples/android-UniversalMusicPlayer#110]
Switch to next song frequently. ANR occur.

traces:

"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 obj=0x7432a3b0 self=0xab282928
  | sysTid=4707 nice=0 cgrp=default sched=0/0 handle=0xf764cb34
  | state=S schedstat=( 0 0 0 ) utm=158 stm=44 core=2 HZ=100
  | stack=0xff48f000-0xff491000 stackSize=8MB
  | held mutexes=
  kernel: __switch_to+0x74/0x8c
  kernel: binder_thread_read+0x8a8/0x102c
  kernel: binder_ioctl_write_read+0x1cc/0x2c4
  kernel: binder_ioctl+0x274/0x6c4
  kernel: compat_sys_ioctl+0xb0/0x162c
  kernel: cpu_switch_to+0x48/0x4c
  native: #00 pc 000442e4  /system/lib/libc.so (__ioctl+8)
  native: #01 pc 000495c5  /system/lib/libc.so (ioctl+14)
  native: #02 pc 0001e86b  /system/lib/libbinder.so (_ZN7android14IPCThreadState14talkWithDriverEb+174)
  native: #03 pc 0001eefb  /system/lib/libbinder.so (_ZN7android14IPCThreadState15waitForResponseEPNS_6ParcelEPi+38)
  native: #04 pc 0001f0c5  /system/lib/libbinder.so (_ZN7android14IPCThreadState8transactEijRKNS_6ParcelEPS1_j+124)
  native: #05 pc 00019ff7  /system/lib/libbinder.so (_ZN7android8BpBinder8transactEjRKNS_6ParcelEPS1_j+30)
  native: #06 pc 00085a75  /system/lib/libmedia.so (???)
  native: #07 pc 0007e5c5  /system/lib/libmedia.so (_ZN7android11MediaPlayer7reset_lEv+32)
  native: #08 pc 0007e63b  /system/lib/libmedia.so (_ZN7android11MediaPlayer5resetEv+18)
  native: #09 pc 000269ad  /system/lib/libmedia_jni.so (???)
  native: #10 pc 000620d7  /data/dalvik-cache/arm/system@framework@boot.oat (Java_android_media_MediaPlayer__1reset__+74)
  at android.media.MediaPlayer._reset(Native method)
  at android.media.MediaPlayer.reset(MediaPlayer.java:1763)
  at com.example.android.uamp.playback.LocalPlayback.createMediaPlayerIfNeeded(LocalPlayback.java:461)
  at com.example.android.uamp.playback.LocalPlayback.play(LocalPlayback.java:183)
  at com.example.android.uamp.playback.PlaybackManager.handlePlayRequest(PlaybackManager.java:77)
  at com.example.android.uamp.playback.PlaybackManager$MediaSessionCallback.onSkipToNext(PlaybackManager.java:309)
  at android.support.v4.media.session.MediaSessionCompat$Callback$StubApi21.onSkipToNext(MediaSessionCompat.java:705)
  at android.support.v4.media.session.MediaSessionCompatApi21$CallbackProxy.onSkipToNext(MediaSessionCompatApi21.java:196)
  at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1228)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5417)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:731)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:621)

**Comment by nic0lette** [comment]
I'm going to close this as obsolete. Let me know if it begins to recur or if you have more details for what processing is taking too long.
