### ISSUE TITLE
Direct crash

### ISSUE THREAD

**Issue by HarryI** [googlesamples/android-UniversalMusicPlayer#115]
Why direct cresh when I install this by android stuido.
There are some errors:
` Caused by: com.google.android.gms.internal.zzsb$zza: No acceptable module found. Local version is 0 and remote version is 0.
 at com.google.android.gms.internal.zzsb.zza(Unknown Source)
at com.google.android.gms.internal.zzni.zzbg(Unknown Source) 
 at com.google.android.gms.internal.zzni.zza(Unknown Source) 
 at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source) 
at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source) 
  at com.example.android.uamp.ui.  ActionBarCastActivity.onCreate   (ActionBarCastActivity.java:141) 
at com.example.android.uamp.ui.   BaseActivity.onCreat   e(BaseActivity.java:49) 
 at com.example.android.uamp.ui.  MusicPlayerActivity.onCreate  (MusicPlayerActivity.java:57) `

Sorry form my bad English. I am form china.

**Comment by lilincpp** [comment]
这个需要Google服务的，所以你得安装一下Google三套件。

**Comment by HarryI** [comment]
谢谢。现在解决了，小米重改了系统的一些配置。
