### ISSUE TITLE
Crash when setting volume after connecting to Cast

### ISSUE THREAD

**Issue by simonschellaert** [googlesamples/android-UniversalMusicPlayer#132]
Hi,

While examining the source code to implement Google Cast in my own app, I discovered that the application (and system UI) crashes every time I execute the following steps:
 1. Make sure no Google Cast session is active before launching the application 
 2. Launch AUMP 
 3. Connect to the Chromecast by tapping on the Cast button in the upper right corner and selecting the preferred device
 4. Click on a volume hardware button
 5. I now get a _System UI has stopped_ dialog and the whole application (and Android UI) crashes and gets me back to the lock screen.

I'm using Android 6.0.1 on a Nexus 5X and a Chromecast v2.
Is anybody else experiencing the same issue or does anyone have any idea about how to fix this?

The log is attached below. I clicked the volume button at 16:17:03.
```
02-16 16:16:47.830 7028-7561/? W/ctxmgr: [AclManager]No 2 for (accnt=account#531576148#, com.google.android.gms(10013):UserLocationProducer, vrsn=10298000, 0, 3pPkg = null ,  3pMdlId = null). Was: 2 for 1, account#531576148#
02-16 16:16:47.832 7028-7561/? W/ctxmgr: [AclManager]No 2 for (accnt=account#959825052#, com.google.android.gms(10013):UserLocationProducer, vrsn=10298000, 0, 3pPkg = null ,  3pMdlId = null). Was: 2 for 1, account#959825052#
02-16 16:16:47.855 4909-4909/? W/Binder_1: type=1400 audit(0.0:3726): avc: denied { ioctl } for path="socket:[106200]" dev="sockfs" ino=106200 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
02-16 16:16:47.855 4909-4909/? W/Binder_1: type=1400 audit(0.0:3727): avc: denied { ioctl } for path="socket:[106200]" dev="sockfs" ino=106200 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
02-16 16:16:47.875 4910-4910/? W/Binder_2: type=1400 audit(0.0:3728): avc: denied { ioctl } for path="socket:[110065]" dev="sockfs" ino=110065 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
02-16 16:16:47.875 4910-4910/? W/Binder_2: type=1400 audit(0.0:3729): avc: denied { ioctl } for path="socket:[110065]" dev="sockfs" ino=110065 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
                                           
                                           --------- beginning of system
02-16 16:16:47.879 4840-6578/? W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=23320, uid=10269 that is not exported from uid 10060
02-16 16:16:47.880 6828-6828/? I/CastMediaRouteProvider: in onDiscoveryRequestChanged: request=DiscoveryRequest{ selector=MediaRouteSelector{ controlCategories=[com.google.android.gms.cast.CATEGORY_CAST/358E83DC, com.google.android.gms.cast.CATEGORY_CAST/CC1AD845, com.google.android.gms.cast.CATEGORY_CAST//urn:x-cast:com.google.cast.media] }, activeScan=true, isValid=true }
02-16 16:16:52.810 4840-7158/? D/NetlinkSocketObserver: NeighborEvent{elapsedMs=744103, 2a02:1812:141c:8500:6238:e0ff:fe02:4865, [6038E0024865], RTM_NEWNEIGH, NUD_STALE}
02-16 16:16:55.319 4840-7411/? D/WifiService: acquireWifiLockLocked: WifiLock{CastMediaRouteProvider type=1 binder=android.os.BinderProxy@780594d}
02-16 16:16:55.321 23320-23320/com.example.android.uamp I/DynamiteModule: Considering local module com.google.android.gms.cast.framework.dynamite:0 and remote module com.google.android.gms.cast.framework.dynamite:7
02-16 16:16:55.321 23320-23320/com.example.android.uamp I/DynamiteModule: Selected remote version of com.google.android.gms.cast.framework.dynamite, version >= 7
02-16 16:16:55.322 23320-23320/com.example.android.uamp I/CastDynamiteModuleImpl: zb created by ClassLoader bzi[DexPathList[[zip file "/data/data/com.google.android.gms/app_chimera/m/00000013/DynamiteModulesC_GmsCore_prodmnc_alldpi_release.apk"],nativeLibraryDirectories=[/data/user/0/com.google.android.gms/app_chimera/m/00000013/n/arm64-v8a, /vendor/lib64, /system/lib64]]].
02-16 16:16:55.324 23320-23320/com.example.android.uamp I/DynamiteModule: Considering local module com.google.android.gms.cast.framework.dynamite:0 and remote module com.google.android.gms.cast.framework.dynamite:7
02-16 16:16:55.325 23320-23320/com.example.android.uamp I/DynamiteModule: Selected remote version of com.google.android.gms.cast.framework.dynamite, version >= 7
02-16 16:16:55.326 23320-23320/com.example.android.uamp I/CastDynamiteModuleImpl: zb created by ClassLoader bzi[DexPathList[[zip file "/data/data/com.google.android.gms/app_chimera/m/00000013/DynamiteModulesC_GmsCore_prodmnc_alldpi_release.apk"],nativeLibraryDirectories=[/data/user/0/com.google.android.gms/app_chimera/m/00000013/n/arm64-v8a, /vendor/lib64, /system/lib64]]].
02-16 16:16:55.331 4840-6844/? W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=23320, uid=10269 that is not exported from uid 10060
02-16 16:16:55.331 7411-7411/? W/Binder_F: type=1400 audit(0.0:3730): avc: denied { ioctl } for path="socket:[110065]" dev="sockfs" ino=110065 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
02-16 16:16:55.331 7411-7411/? W/Binder_F: type=1400 audit(0.0:3731): avc: denied { ioctl } for path="socket:[110065]" dev="sockfs" ino=110065 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
02-16 16:16:55.335 6828-6828/? I/CastMediaRouteProvider: in onDiscoveryRequestChanged: request=DiscoveryRequest{ selector=MediaRouteSelector{ controlCategories=[com.google.android.gms.cast.CATEGORY_CAST/358E83DC, com.google.android.gms.cast.CATEGORY_CAST/CC1AD845, com.google.android.gms.cast.CATEGORY_CAST//urn:x-cast:com.google.cast.media] }, activeScan=false, isValid=true }
02-16 16:16:55.345 6828-7183/? I/CastService: [instance-7] Google Play services client: 9452000, Google Play services APK: 10298000
02-16 16:16:55.346 6828-7183/? I/CastService: [instance-7] acquireDeviceController by com.example.android.uamp
02-16 16:16:55.524 4840-4849/? I/art: Background partial concurrent mark sweep GC freed 32561(2016KB) AllocSpace objects, 12(336KB) LOS objects, 33% free, 29MB/44MB, paused 899us total 104.321ms
02-16 16:16:55.527 4840-4847/? W/JavaBinder: Binder has been finalized when calling linkToDeath() with recip=0x7fa82deee8)
02-16 16:16:55.553 6828-11555/? I/CastDeviceController: [controller-0021 API] calling Listener.onConnected(true)
02-16 16:16:55.556 6828-7181/? I/CastService: [instance-7] launchApplicationWithOptions: com.example.android.uamp CC1AD845 LaunchOptions(relaunchIfRunning=false, language=nl-NL)
02-16 16:16:55.558 6828-11555/? I/CastDeviceController: [controller-0021 API] launchApplicationInternal. id=CC1AD845, options=LaunchOptions(relaunchIfRunning=false, language=nl-NL)
02-16 16:16:55.559 6828-11555/? I/CastDeviceController: [controller-0021 API] joinApplicationInternal: appId:CC1AD845 sessionId:null joinOptions:joinOptions(connectionType=STRONG)
02-16 16:16:55.601 6828-11555/? I/CastDeviceController: [controller-0021 API] launchApplicationInternal. id=CC1AD845, options=LaunchOptions(relaunchIfRunning=true, language=nl-NL)
02-16 16:16:55.710 6828-11555/? I/CastService: [instance-7] onApplicationConnected: com.example.android.uamp applicationId: CC1AD845, name: Default Media Receiver, images.count: 0, namespaces.count: 2, senderAppIdentifier: null, senderAppLaunchUrl: null Ready To Cast 4df8e093-0ffd-4ad2-bebd-763e4f5a31fb true
02-16 16:16:55.718 4840-7402/? I/MediaFocusControl:  AudioFocus  requestAudioFocus() from android.media.AudioManager@fdc38b req=3flags=0x0
02-16 16:16:55.744 23320-23320/com.example.android.uamp E/AudioAttributes: Invalid stream type -1 for AudioAttributes
02-16 16:16:55.746 4840-7240/? I/MediaFocusControl:  AudioFocus  abandonAudioFocus() from android.media.AudioManager@622cc68com.example.android.uamp.playback.LocalPlayback@788e881
02-16 16:16:55.770 4840-7158/? D/NetlinkSocketObserver: NeighborEvent{elapsedMs=747063, fe80::6238:e0ff:fe02:4865, [6038E0024865], RTM_NEWNEIGH, NUD_STALE}
02-16 16:16:55.893 6828-6838/? I/art: Background partial concurrent mark sweep GC freed 172799(9MB) AllocSpace objects, 25(948KB) LOS objects, 38% free, 26MB/42MB, paused 807us total 125.275ms
02-16 16:16:55.958 6828-11555/? I/CastDeviceController: [controller-0020 MRP] calling Listener.onConnected(true)
                                                        
                                                        --------- beginning of crash
02-16 16:17:03.689 20413-20442/? E/AndroidRuntime: FATAL EXCEPTION: VolumeDialogController
                                                   Process: com.android.systemui, PID: 20413
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                       at com.android.systemui.volume.VolumeDialogController$MediaSessionsCallbacks.onRemoteVolumeChanged(VolumeDialogController.java:871)
                                                       at com.android.systemui.volume.MediaSessions.onRemoteVolumeChangedH(MediaSessions.java:121)
                                                       at com.android.systemui.volume.MediaSessions.-wrap1(MediaSessions.java)
                                                       at com.android.systemui.volume.MediaSessions$H.handleMessage(MediaSessions.java:363)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
02-16 16:17:03.694 6828-11555/? I/CastDeviceController: [controller-0020 MRP] setVolumeInternal; volume:0.550000, currentVolume:0.500000, currentMuteSTate:false
02-16 16:17:03.746 4840-6511/? I/OpenGLRenderer: Initialized EGL, version 1.4
02-16 16:17:04.276 6828-11555/? I/CastDeviceController: [controller-0022 RCNController] calling Listener.onConnected(true)
02-16 16:17:04.351 6828-11555/? I/CastDeviceController: [controller-0022 RCNController] joinApplicationInternal: appId:CC1AD845 sessionId: joinOptions:joinOptions(connectionType=INVISIBLE)
02-16 16:17:04.380 6828-11555/? I/CastDeviceController: [controller-0022 RCNController] joinApplicationInternal: appId:CC1AD845 sessionId: joinOptions:joinOptions(connectionType=INVISIBLE)
02-16 16:17:04.610 4840-7158/? D/NetlinkSocketObserver: NeighborEvent{elapsedMs=755903, 192.168.1.1, [6038E0024865], RTM_NEWNEIGH, NUD_STALE}
``

**Comment by rerdavies** [comment]
I ran into the same problem in my app. I followed the advice in 
[this problem report](https://github.com/googlesamples/android-UniversalMusicPlayer/issues/165)

Interestingly, the problem went away.

The specific fix is to change which constructor you use for MediaSessionCompat:

```
ComponentName mbrComponent = new ComponentName(getApplicationContext().getPackageName(),
          MediaButtonReceiver.class.getName());
   MediaSessionCompat   mSession = new MediaSessionCompat(this, "MusicService", mbrComponent, null);
```
(and presumably to make sure you have the Media Button receiver declared in the manifest already, which I had done previously):

```
<receiver android:name="android.support.v4.media.session.MediaButtonReceiver" >
    <intent-filter>
        <action android:name="android.intent.action.MEDIA_BUTTON" />
    </intent-filter>
</receiver>
```

This appears to still be a bug or a weakness in the current Cast SDK as of July 2018.

Version info: 
    implementation 'com.google.android.gms:play-services-cast-framework:15.0.1'
    implementation 'com.android.support:mediarouter-v7:27.1.1'

Android version: 7.0
Device: 
   Asus Zenbook 8.0.

User reports of an identical crash of the system UI when casting with Google Play Music suggest that the issue may be OEM device related (or perhaps Android version related), and is fairly device-specific. Oddly volume keys do not work on the currrent version of Google Play Music as of July 2018 suggesting that Google Play Music developers may have disabled the Cast SDK behaviour deliberately to avoid crashes in the field.  I am not able to replicate the crash with google play music on my Asus Zenbook 8.0, but the media buttons just control MUSIC_STREAM volume and have no effect on the target Chromecast device.

Further details of interest: my app uses code lifted from the UniversalMusicPlayer app. However, I intercept media keys in the application. Pre-workaround: keys events are not recevied in the application, and the System UI crashes as descrbied in the original post; post-workaround: media keys are intercepted by the application, and I end up routing the events to my own service that applies the volume up/volume down events to the session using my code. (I had existing code to handle media key events already since I also "cast" to UPNP devices outside the MediaRouter framework). Hope that helps.

Behavior in the background is as-of-yet untested. And I am, frankly not very comfortable with the workaround given the heavy churn in these APIS in Android v21 to v28.  And it's unpleasant to test because (1) the only device I have with media keys is an android tv device, and tv support hasn't been addressed in the app yet. And (2), none of this can be tested in the emulator because you can't cast from emulated devices. Any guidance would be much appreciated.
