### ISSUE TITLE
Android leanback module crashes on starting up

### ISSUE THREAD

**Issue by mrThinBone** [googlesamples/android-UniversalMusicPlayer#202]
Hi, when I launch app to Android TV Box by click "run" on Android Studio or manually copy apk then install & open, there's been always crashes.
I figured out that at the first time, MusicPlayerActivity (which is phone launcher) has been launched. But in subsequent, TvBrowseActivity(which is leanback launcher) will be launched instead.
How do I make it will always launch TvBrowseActivity on TV devices?

> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.uamp/com.example.android.uamp.ui.MusicPlayerActivity}: java.lang.RuntimeException: com.google.android.gms.dynamite.DynamiteModule$zzc: No acceptable module found. Local version is 0 and remote version is 0.
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:733)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623)
                                                  Caused by: java.lang.RuntimeException: com.google.android.gms.dynamite.DynamiteModule$zzc: No acceptable module found. Local version is 0 and remote version is 0.
                                                     at com.google.android.gms.internal.zzaui.zzan(Unknown Source)
                                                     at com.google.android.gms.internal.zzaui.zza(Unknown Source)
                                                     at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source)
                                                     at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source)
                                                     at com.example.android.uamp.ui.ActionBarCastActivity.onCreate(ActionBarCastActivity.java:148)
                                                     at com.example.android.uamp.ui.BaseActivity.onCreate(BaseActivity.java:49)
                                                     at com.example.android.uamp.ui.MusicPlayerActivity.onCreate(MusicPlayerActivity.java:58)
                                                     at android.app.Activity.performCreate(Activity.java:6251)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5422) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:733) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623) 
                                                  Caused by: com.google.android.gms.dynamite.DynamiteModule$zzc: No acceptable module found. Local version is 0 and remote version is 0.
                                                     at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source)
                                                     at com.google.android.gms.internal.zzaui.zzan(Unknown Source) 
                                                     at com.google.android.gms.internal.zzaui.zza(Unknown Source) 
                                                     at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source) 
                                                     at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source) 
                                                     at com.example.android.uamp.ui.ActionBarCastActivity.onCreate(ActionBarCastActivity.java:148) 
                                                     at com.example.android.uamp.ui.BaseActivity.onCreate(BaseActivity.java:49) 
                                                     at com.example.android.uamp.ui.MusicPlayerActivity.onCreate(MusicPlayerActivity.java:58) 
                                                     at android.app.Activity.performCreate(Activity.java:6251) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5422) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:733) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623)

**Comment by mrThinBone** [comment]
Is this the right solution https://stackoverflow.com/a/30059511?

**Comment by nic0lette** [comment]
The crash is related to Google Play Services not being ready as it tries to load the Cast module. Do you have Google Play Services on your device?

**Comment by mrThinBone** [comment]
yes, I do, also the lastest version(**11.9.75**).
