### ISSUE TITLE
Crash after tapping an item after rotating

### ISSUE THREAD

**Issue by nic0lette** [googlesamples/android-UniversalMusicPlayer#226]
This happens because both `MainActivity` and `MediaItemFragment` are recreated from the saved instance state, but the click handler isn't connected again.

It's usually connected in [`MediaItemFragment.newInstance`](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/9ef94f2cb6da70d90c8b1e9b4a9114d1a6d11567/app/src/main/java/com/example/android/uamp/MediaItemFragment.kt#L57).

Stack trace:

```06-29 16:07:24.142 11602-11602/com.example.android.uamp.next E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.uamp.next, PID: 11602
    kotlin.UninitializedPropertyAccessException: lateinit property browsableItemClicked has not been initialized
        at com.example.android.uamp.MediaItemFragment.access$getBrowsableItemClicked$p(MediaItemFragment.kt:36)
        at com.example.android.uamp.MediaItemFragment$listAdapter$1.invoke(MediaItemFragment.kt:43)
        at com.example.android.uamp.MediaItemFragment$listAdapter$1.invoke(MediaItemFragment.kt:36)
        at com.example.android.uamp.MediaViewHolder$1.onClick(MediaItemAdapter.kt:70)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)```

**Comment by nic0lette** [comment]
This should be fixed now.
