### ISSUE TITLE
App closes after launch (IllegalCharsetNameException)

### ISSUE THREAD

**Issue by 13kz** [googlesamples/android-UniversalMusicPlayer#233]
_android-UniversalMusicPlayer Sample
Huawei Android 6.0_

An Exception is thrown with the sample. I notice this crash on the Huawei 6.0. Not on my emulator Nexus 5 API 26 (8.0.0)
**Below the stacktrace**
Fatal Exception: java.nio.charset.IllegalCharsetNameException: java.nio.charset.CharsetICU[UTF-8]
       at java.nio.charset.Charset.checkCharsetName(Charset.java:201)
       at java.nio.charset.Charset.forName(Charset.java:295)
       at java.net.URLEncoder.encode(URLEncoder.java:57)
       at com.zimberland.kotlin.sdj.media.library.BrowseTree.<init>(BrowseTree.kt:129)
       at com.zimberland.kotlin.sdj.media.MusicService$browseTree$2.invoke(MusicService.kt:77)
       at com.zimberland.kotlin.sdj.media.MusicService$browseTree$2.invoke(MusicService.kt:62)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at com.zimberland.kotlin.sdj.media.MusicService.getBrowseTree(MusicService.kt)
       at com.zimberland.kotlin.sdj.media.MusicService.access$getBrowseTree$p(MusicService.kt:62)
       at com.zimberland.kotlin.sdj.media.MusicService$onLoadChildren$resultsSent$1.invoke(MusicService.kt:192)
       at com.zimberland.kotlin.sdj.media.MusicService$onLoadChildren$resultsSent$1.invoke(MusicService.kt:62)
       at com.zimberland.kotlin.sdj.media.library.AbstractMusicSource.setState(MusicSource.kt:91)
       at com.zimberland.kotlin.sdj.media.library.JsonSource$1.invoke(JsonSource.kt:67)
       at com.zimberland.kotlin.sdj.media.library.JsonSource$1.invoke(JsonSource.kt:59)
       at com.zimberland.kotlin.sdj.media.library.UpdateCatalogTask.onPostExecute(JsonSource.kt:125)
       at com.zimberland.kotlin.sdj.media.library.UpdateCatalogTask.onPostExecute(JsonSource.kt:78)
       at android.os.AsyncTask.finish(AsyncTask.java:679)
       at android.os.AsyncTask.access$500(AsyncTask.java:180)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:696)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5621)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by hamzabm** [comment]
same for me

**Comment by 13kz** [comment]
I found a way to avoid it. Is it the best solution I don't know. Hope someone else I will find another solution. Maybe better than mine :)

In **[BrowseTree.kt](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/23ab516133f75abcd243c7bbd5f15f2f1d8cbb35/media/src/main/java/com/example/android/uamp/media/library/BrowseTree.kt)** file line 66 and 86, media item album url encoding cause the crash. I just retrieve the album from media item without encoding.

**Comment by nic0lette** [comment]
Thank you! I'll see if there might be a slightly more elegant way to do this and hopefully make an update later today.

**Comment by 13kz** [comment]
Nice. Thanks. By the way good job. Really nice project.

**Comment by nic0lette** [comment]
I'll close this for now. Let me know if it reoccurs. Thanks again for the report.
