### ISSUE TITLE
Window.tag =null when i play HLS

### ISSUE THREAD

**Issue by Huangjiaqi0421** [googlesamples/android-UniversalMusicPlayer#253]
**Issue description**
I add dependencies 
`    api "com.google.android.exoplayer:exoplayer-hls:$exoplayer_version"
`
and change the fun to support HLS media

```
fun MediaMetadataCompat.toMediaSource(dataSourceFactory: DataSource.Factory):MediaSource  {
    @C.ContentType
    val type = Util.inferContentType(mediaUri)
    return when(type){
        C.TYPE_HLS -> {
             HlsMediaSource.Factory(dataSourceFactory)
                    .setTag(fullDescription)
                    .createMediaSource(mediaUri)
        }
        else -> {
             ExtractorMediaSource.Factory(dataSourceFactory)
                    .setTag(fullDescription)
                    .createMediaSource(mediaUri)
        }
    }

}
```

but, When i try to get window tag in `TimelineQueueNavigator.getMediaDescription` i always get null .

```
override fun getMediaDescription(player: Player, windowIndex: Int): MediaDescriptionCompat =
            player.currentTimeline
                    .getWindow(windowIndex, window, true).tag as MediaDescriptionCompat
```

**error log**
```
10-10 16:28:42.960 1859-1859/com.example.android.uamp.next E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.uamp.next, PID: 1859
    kotlin.TypeCastException: null cannot be cast to non-null type android.support.v4.media.MediaDescriptionCompat
        at com.example.android.uamp.media.UampQueueNavigator.getMediaDescription(MusicService.kt:323)
        at com.google.android.exoplayer2.ext.mediasession.TimelineQueueNavigator.publishFloatingQueueWindow(TimelineQueueNavigator.java:189)
        at com.google.android.exoplayer2.ext.mediasession.TimelineQueueNavigator.onTimelineChanged(TimelineQueueNavigator.java:107)
        at com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector$ExoPlayerEventListener.onTimelineChanged(MediaSessionConnector.java:682)
        at com.example.android.uamp.media.audiofocus.AudioFocusExoPlayerDecorator$playerEventListener$1.onTimelineChanged(AudioFocusExoPlayerDecorator.kt:199)
        at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.notifyListeners(ExoPlayerImpl.java:746)
        at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:681)
        at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:622)
        at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:567)
        at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:109)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5968)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:800)
```

**Comment by tyzero** [comment]
I got the same issue

**Comment by nic0lette** [comment]
It looks like this may be an issue with ExoPlayer. Could you create an issue in the [ExoPlayer project](https://github.com/google/ExoPlayer) please?

**Comment by hungntv** [comment]
> It looks like this may be an issue with ExoPlayer. Could you create an issue in the [ExoPlayer project](https://github.com/google/ExoPlayer) please?

I did [https://github.com/google/ExoPlayer/issues/6625](https://github.com/google/ExoPlayer/issues/6625)
