### ISSUE TITLE
How to give support for Android Kitkat 4.4.4? Its api level is 19 lesser than 21.

### ISSUE THREAD

**Issue by Jayiitb** [googlesamples/android-UniversalMusicPlayer#76]
Any suggestion on how to implement same thing on API version lower than 21. Or any good example like this one.

Thanks a lot for this wonderful sample app.

**Comment by izbrannick** [comment]
Actually grandle script says: minSdkVersion 17, så it should support down to 17, but it does not, this is clearly a bug

**Comment by pawpawhe** [comment]
I think I got the same error;

04-01 17:32:42.230 5464-5464/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.example.android.uamp, PID: 5464
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.uamp/com.example.android.uamp.ui.MusicPlayerActivity}: android.view.InflateException: Binary XML file line #25: Error inflating class android.support.v7.widget.Toolbar
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2258)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:147)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5135)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: android.view.InflateException: Binary XML file line #25: Error inflating class android.support.v7.widget.Toolbar
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:623)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                     at android.view.LayoutInflater.parseInclude(LayoutInflater.java:842)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:748)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267)
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129)
                                                     at com.example.android.uamp.ui.MusicPlayerActivity.onCreate(MusicPlayerActivity.java:60)
                                                     at android.app.Activity.performCreate(Activity.java:5361)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2163)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2258) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:147) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5135) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                     at java.lang.reflect.Constructor.constructNative(Native Method)
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:597)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                     at android.view.LayoutInflater.parseInclude(LayoutInflater.java:842) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:748) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267) 
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129) 
                                                     at com.example.android.uamp.ui.MusicPlayerActivity.onCreate(MusicPlayerActivity.java:60) 
                                                     at android.app.Activity.performCreate(Activity.java:5361) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2163) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2258) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:147) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5135) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v19/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020016
                                                     at android.content.res.Resources.loadDrawable(Resources.java:2179)
                                                     at android.content.res.Resources.loadDrawable(Resources.java:2102)
                                                     at android.content.res.Resources.getDrawable(Resources.java:710)
                                                     at android.support.v7.widget.TintResources.superGetDrawable(TintResources.java:48)
                                                     at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:374)
                                                     at android.support.v7.widget.TintResources.getDrawable(TintResources.java:44)
                                                     at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
                                                     at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:180)
                                                     at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:173)
                                                     at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:60)
                                                     at android.support.v7.widget.Toolbar.<init>(Toolbar.java:254)
                                                     at android.support.v7.widget.Toolbar.<init>(Toolbar.java:196)
                                                     at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:597) 
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                     at android.view.LayoutInflater.parseInclude(LayoutInflater.java:842) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:748) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267) 
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129) 
                                                     at com.example.android.uamp.ui.MusicPlayerActivity.onCreate(MusicPlayerActivity.java:60) 
                                                     at android.app.Activity.performCreate(Activity.java:5361) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2163) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2258) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:147) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5135) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
                                                     at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:935)
                                                     at android.graphics.drawable.Drawable.createFromXml(Drawable.java:879)
                                                     at android.content.res.Resources.createFromXml(Resources.java:2555)
