### ISSUE TITLE
exceptions of new build while starting on a lvl 17 device

### ISSUE THREAD

**Issue by romanoss** [googlesamples/android-UniversalMusicPlayer#78]
Hi - I tried to run the current source of uamp on a 7' tablet with android lvl 17 and got this - please take a look

thx Roman

03-29 00:31:20.851 3566-3566/com.example.android.uamp D/dalvikvm: Late-enabling CheckJNI
03-29 00:31:21.062 3566-3566/com.example.android.uamp E/dalvikvm: Could not find class 'android.view.accessibility.CaptioningManager', referenced from method com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.registerCaptionListener
03-29 00:31:21.062 3566-3566/com.example.android.uamp W/dalvikvm: VFY: unable to resolve check-cast 3208 (Landroid/view/accessibility/CaptioningManager;) in Lcom/google/android/libraries/cast/companionlibrary/cast/VideoCastManager;
03-29 00:31:21.062 3566-3566/com.example.android.uamp D/dalvikvm: VFY: replacing opcode 0x1f at 0x000a
03-29 00:31:21.093 3566-3566/com.example.android.uamp W/dalvikvm: Unable to resolve superclass of Lcom/google/android/libraries/cast/companionlibrary/cast/VideoCastManager$34; (3207)
03-29 00:31:21.093 3566-3566/com.example.android.uamp W/dalvikvm: Link of class 'Lcom/google/android/libraries/cast/companionlibrary/cast/VideoCastManager$34;' failed
03-29 00:31:21.093 3566-3566/com.example.android.uamp D/dalvikvm: DexOpt: unable to opt direct call 0x884b at 0x0e in Lcom/google/android/libraries/cast/companionlibrary/cast/VideoCastManager;.registerCaptionListener
03-29 00:31:21.093 3566-3566/com.example.android.uamp I/dalvikvm: Could not find method android.app.Notification$Builder.setLocalOnly, referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zza
03-29 00:31:21.093 3566-3566/com.example.android.uamp W/dalvikvm: VFY: unable to resolve virtual method 305: Landroid/app/Notification$Builder;.setLocalOnly (Z)Landroid/app/Notification$Builder;
03-29 00:31:21.093 3566-3566/com.example.android.uamp D/dalvikvm: VFY: replacing opcode 0x6e at 0x00c8
03-29 00:31:21.093 3566-3566/com.example.android.uamp I/dalvikvm: DexOpt: access denied from Lcom/google/android/gms/common/GooglePlayServicesUtil; to field Landroid/app/Notification;.extras
03-29 00:31:21.093 3566-3566/com.example.android.uamp W/dalvikvm: VFY: unable to resolve instance field 16
03-29 00:31:21.093 3566-3566/com.example.android.uamp D/dalvikvm: VFY: replacing opcode 0x54 at 0x00e7
03-29 00:31:21.101 3566-3566/com.example.android.uamp I/dalvikvm: Could not find method android.os.UserManager.getApplicationRestrictions, referenced from method com.google.android.gms.common.zze.zzaq
03-29 00:31:21.101 3566-3566/com.example.android.uamp W/dalvikvm: VFY: unable to resolve virtual method 1612: Landroid/os/UserManager;.getApplicationRestrictions (Ljava/lang/String;)Landroid/os/Bundle;
03-29 00:31:21.101 3566-3566/com.example.android.uamp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0012
03-29 00:31:21.101 3566-3566/com.example.android.uamp E/dalvikvm: Could not find class 'android.app.AppOpsManager', referenced from method com.google.android.gms.common.zze.zzb
03-29 00:31:21.101 3566-3566/com.example.android.uamp W/dalvikvm: VFY: unable to resolve check-cast 36 (Landroid/app/AppOpsManager;) in Lcom/google/android/gms/common/zze;
03-29 00:31:21.101 3566-3566/com.example.android.uamp D/dalvikvm: VFY: replacing opcode 0x1f at 0x000e
03-29 00:31:21.109 3566-3566/com.example.android.uamp I/dalvikvm: Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.zze.zzi
03-29 00:31:21.109 3566-3566/com.example.android.uamp W/dalvikvm: VFY: unable to resolve virtual method 576: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
03-29 00:31:21.109 3566-3566/com.example.android.uamp D/dalvikvm: VFY: replacing opcode 0x6e at 0x000b
03-29 00:31:21.203 3566-3566/com.example.android.uamp I/MediaRouter: Found default route: MediaRouter.RouteInfo{ uniqueId=android/.support.v7.media.SystemMediaRouteProvider:DEFAULT_ROUTE, name=Tablet, description=null, iconUri=null, enabled=true, connecting=false, connectionState=0, canDisconnect=false, playbackType=0, playbackStream=3, deviceType=0, volumeHandling=1, volume=10, volumeMax=15, presentationDisplayId=-1, extras=null, settingsIntent=null, providerPackageName=android }
03-29 00:31:21.242 3566-3566/com.example.android.uamp E/dalvikvm: Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method com.example.android.uamp.ui.BaseActivity.onCreate
03-29 00:31:21.242 3566-3566/com.example.android.uamp W/dalvikvm: VFY: unable to resolve new-instance 31 (Landroid/app/ActivityManager$TaskDescription;) in Lcom/example/android/uamp/ui/BaseActivity;
03-29 00:31:21.242 3566-3566/com.example.android.uamp D/dalvikvm: VFY: replacing opcode 0x22 at 0x0016
03-29 00:31:21.242 3566-3566/com.example.android.uamp D/dalvikvm: DexOpt: unable to opt direct call 0x0091 at 0x34 in Lcom/example/android/uamp/ui/BaseActivity;.onCreate
03-29 00:31:21.265 3566-3566/com.example.android.uamp W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
03-29 00:31:21.265 3566-3566/com.example.android.uamp I/dalvikvm: Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
03-29 00:31:21.265 3566-3566/com.example.android.uamp W/dalvikvm: VFY: unable to resolve interface method 27770: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
03-29 00:31:21.265 3566-3566/com.example.android.uamp D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
03-29 00:31:21.273 3566-3566/com.example.android.uamp I/dalvikvm: Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
03-29 00:31:21.273 3566-3566/com.example.android.uamp W/dalvikvm: VFY: unable to resolve interface method 27774: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
03-29 00:31:21.273 3566-3566/com.example.android.uamp D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
03-29 00:31:21.320 3566-3570/com.example.android.uamp D/dalvikvm: GC_CONCURRENT freed 310K, 18% free 5443K/6592K, paused 1ms+3ms, total 89ms
03-29 00:31:21.351 3566-3566/com.example.android.uamp I/dalvikvm: Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
03-29 00:31:21.351 3566-3566/com.example.android.uamp W/dalvikvm: VFY: unable to resolve virtual method 643: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
03-29 00:31:21.351 3566-3566/com.example.android.uamp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
03-29 00:31:21.351 3566-3566/com.example.android.uamp I/dalvikvm: Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
03-29 00:31:21.351 3566-3566/com.example.android.uamp W/dalvikvm: VFY: unable to resolve virtual method 665: Landroid/content/res/TypedArray;.getType (I)I
03-29 00:31:21.351 3566-3566/com.example.android.uamp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
03-29 00:31:21.367 3566-3566/com.example.android.uamp E/VdcInflateDelegate: Exception while inflating <vector>
                                                                            org.xmlpull.v1.XmlPullParserException: Binary XML file line #17<vector> tag requires viewportWidth > 0
                                                                                at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:535)
                                                                                at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:472)
                                                                                at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:436)
                                                                                at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:829)
                                                                                at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:303)
                                                                                at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:178)
                                                                                at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:173)
                                                                                at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:60)
                                                                                at android.support.v7.widget.Toolbar.<init>(Toolbar.java:254)
                                                                                at android.support.v7.widget.Toolbar.<init>(Toolbar.java:196)
                                                                                at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                                at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                                at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:226)
                                                                                at android.support.v7.app.AppCompatViewInflater.createViewFromTag(AppCompatViewInflater.java:175)
                                                                                at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:146)
                                                                                at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:963)
                                                                                at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1022)
                                                                                at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:681)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
                                                                                at android.view.LayoutInflater.parseInclude(LayoutInflater.java:846)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                                at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267)
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129)
                                                                                at com.example.android.uamp.ui.MusicPlayerActivity.onCreate(MusicPlayerActivity.java:60)
                                                                                at android.app.Activity.performCreate(Activity.java:5326)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2225)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316)
                                                                                at android.app.ActivityThread.access$700(ActivityThread.java:158)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                at android.os.Looper.loop(Looper.java:176)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5365)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
                                                                                at dalvik.system.NativeStart.main(Native Method)
03-29 00:31:21.367 3566-3566/com.example.android.uamp D/AndroidRuntime: Shutting down VM
03-29 00:31:21.367 3566-3566/com.example.android.uamp W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4105c930)
03-29 00:31:21.382 3566-3566/com.example.android.uamp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.uamp/com.example.android.uamp.ui.MusicPlayerActivity}: android.view.InflateException: Binary XML file line #25: Error inflating class android.support.v7.widget.Toolbar
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2262)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316)
                                                                            at android.app.ActivityThread.access$700(ActivityThread.java:158)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                            at android.os.Looper.loop(Looper.java:176)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5365)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:511)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
                                                                            at dalvik.system.NativeStart.main(Native Method)
                                                                         Caused by: android.view.InflateException: Binary XML file line #25: Error inflating class android.support.v7.widget.Toolbar
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
                                                                            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:846)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267)
                                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129)
                                                                            at com.example.android.uamp.ui.MusicPlayerActivity.onCreate(MusicPlayerActivity.java:60)
                                                                            at android.app.Activity.performCreate(Activity.java:5326)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2225)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316) 
                                                                            at android.app.ActivityThread.access$700(ActivityThread.java:158) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                            at android.os.Looper.loop(Looper.java:176) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5365) 
                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
                                                                            at dalvik.system.NativeStart.main(Native Method) 
                                                                         Caused by: java.lang.reflect.InvocationTargetException
                                                                            at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:593)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:752) 
                                                                            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:846) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:742) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:760) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267) 
                                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129) 
                                                                            at com.example.android.uamp.ui.MusicPlayerActivity.onCreate(MusicPlayerActivity.java:60) 
                                                                            at android.app.Activity.performCreate(Activity.java:5326) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2225) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316) 
                                                                            at android.app.ActivityThread.access$700(ActivityThread.java:158) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                            at android.os.Looper.loop(Looper.java:176) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5365) 
                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
                                                                            at dalvik.system.NativeStart.main(Native Method) 
                                                                         Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020016
                                                                            at android.content.res.Resources.loadDrawable(Resources.java:2842)
                                                                            at android.content.res.Resources.getDrawable(Resources.java:1521)
                                                                            at android.support.v7.widget.TintResources.superGetDrawable(TintResources.java:48)
                                                                            at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:374)
                                                                            at android.support.v7.widget.TintResources.getDrawable(TintResources.java:44)
                                                                            at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
                                                                            at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:180)
                                                                            at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:173)
                                                                            at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:60)
                                                                            at android.support.v7.widget.Toolbar.<init>(Toolbar.java:254)
                                                                            at android.support.v7.widget.Toolbar.<init>(Toolbar.java:196)
                                                                            at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                            at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:593) 
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:752) 
                                                                            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:846) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:742) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:760) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267) 
                                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129) 
                                                                            at com.example.android.uamp.ui.MusicPlayerActivity.onCreate(MusicPlayerActivity.java:60) 
                                                                            at android.app.Activity.performCreate(Activity.java:5326) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2225) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316) 
                                                                            at android.app.ActivityThread.access$700(ActivityThread.java:158) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                            at android.os.Looper.loop(Looper.java:176) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5365) 
                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
                                                                            at dalvik.system.NativeStart.main(Native Method) 
                                                                         Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
                                                                            at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:917)
                                                                            at android.graphics.drawable.Drawable.createFromXml(Drawable.java:858)
                                                                            at android.content.res.Resources.loadDrawable(Resources.java:2839)
                                                                            at android.content.res.Resources.getDrawable(Resources.java:1521) 
                                                                            at android.support.v7.widget.TintResources.superGetDrawable(TintResources.java:48) 
                                                                            at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:374) 
                                                                            at android.support.v7.widget.TintResources.getDrawable(TintResources.java:44) 
                                                                            at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323) 
                                                                            at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:180) 
                                                                            at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:173) 
                                                                            at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:60) 
                                                                            at android.support.v7.widget.Toolbar.<init>(Toolbar.java:254) 
                                                                            at android.support.v7.widget.Toolbar.<init>(Toolbar.java:196) 
                                                                            at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                            at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:593) 
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:752) 
                                                                            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:846) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:742) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:760) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267) 
                                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129) 
                                                                            at com.example.android.uamp.ui.MusicPlayerActivity.onCreate(MusicPlayerActivity.java:60) 
                                                                            at android.app.Activity.performCreate(Activity.java:5326) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2225) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316) 
                                                                            at android.app.ActivityThread.access$700(ActivityThread.java:158) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                            at android.os.Looper.loop(Looper.java:176) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5365) 
                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
                                                                            at dalvik.system.NativeStart.main(Native Method) 
03-29 00:31:21.414 3566-3570/com.example.android.uamp D/dalvikvm: GC_CONCURRENT freed 329K, 18% free 5527K/6736K, paused 1ms+4ms, total 34ms
03-29 00:31:24.273 3566-3566/? I/Process: Sending signal. PID: 3566 SIG: 9

**Comment by nic0lette** [comment]
@romanoss Can you try again with the latest build?
