### ISSUE TITLE
Crash！！！！！！！！！！！！

### ISSUE THREAD

**Issue by zhousysu** [googlesamples/android-UniversalMusicPlayer#94]
```
08-16 10:42:46.643 30212-30212/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example.android.uamp, PID: 30212
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.uamp/com.example.android.uamp.ui.MusicPlayerActivity}: java.lang.RuntimeException: com.google.android.gms.internal.zzsb$zza: No acceptable module found. Local version is 0 and remote version is 0.
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2641)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2710)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:179)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1561)
                                                       at android.os.Handler.dispatchMessage(Handler.java:111)
                                                       at android.os.Looper.loop(Looper.java:194)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5803)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1010)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
                                                    Caused by: java.lang.RuntimeException: com.google.android.gms.internal.zzsb$zza: No acceptable module found. Local version is 0 and remote version is 0.
                                                       at com.google.android.gms.internal.zzni.zzbg(Unknown Source)
                                                       at com.google.android.gms.internal.zzni.zza(Unknown Source)
                                                       at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source)
                                                       at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source)
                                                       at com.example.android.uamp.ui.ActionBarCastActivity.onCreate(ActionBarCastActivity.java:141)
                                                       at com.example.android.uamp.ui.BaseActivity.onCreate(BaseActivity.java:49)
                                                       at com.example.android.uamp.ui.MusicPlayerActivity.onCreate(MusicPlayerActivity.java:57)
                                                       at android.app.Activity.performCreate(Activity.java:6107)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2594)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2710) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:179) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1561) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                       at android.os.Looper.loop(Looper.java:194) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5803) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1010) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805) 
                                                    Caused by: com.google.android.gms.internal.zzsb$zza: No acceptable module found. Local version is 0 and remote version is 0.
                                                       at com.google.android.gms.internal.zzsb.zza(Unknown Source)
                                                       at com.google.android.gms.internal.zzni.zzbg(Unknown Source) 
                                                       at com.google.android.gms.internal.zzni.zza(Unknown Source) 
                                                       at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source) 
                                                       at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source) 
                                                       at com.example.android.uamp.ui.ActionBarCastActivity.onCreate(ActionBarCastActivity.java:141) 
                                                       at com.example.android.uamp.ui.BaseActivity.onCreate(BaseActivity.java:49) 
                                                       at com.example.android.uamp.ui.MusicPlayerActivity.onCreate(MusicPlayerActivity.java:57) 
                                                       at android.app.Activity.performCreate(Activity.java:6107) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2594) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2710) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:179) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1561) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                       at android.os.Looper.loop(Looper.java:194) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5803) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1010) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805) 
```

**Comment by asbadve** [comment]
Same here!! @zhousysu have you found the solution?

**Comment by smishra2** [comment]
What device are you running this on?

**Comment by zhousysu** [comment]
@smishra2 Meizu MX4

**Comment by zhousysu** [comment]
@asbadve No. I don't know how to fix it.

**Comment by smishra2** [comment]
Your phone has to have Google Play Services from the Play Store. That may be your issue.

**Comment by zhousysu** [comment]
@smishra2 aha.Thanks!! I got it!!!

**Comment by asbadve** [comment]
@smishra2 Well my device is motog2 and google play service(version 9.2.56) is up to date.device OS is 23.

**Comment by heiheiyuan** [comment]
Have you fixed it after installatino?

**Comment by smishra2** [comment]
The latest version of Google Play services is 9.4 (https://developers.google.com/android/guides/releases).

**Comment by heiheiyuan** [comment]
@smishra2 Thank you so much!!! My device can not update automatically.So sad...

**Comment by asbadve** [comment]
@smishra2 Sorry about that.I was in the wrong intention that the play service shows notification to update.I did't know that to update the google play service you need to install other app like [this](https://play.google.com/store/apps/details?id=com.weberdo.apps.serviceinfo&hl=en).

**Comment by daedamr** [comment]
So does this mean that for users with older play services the app will simply crash? Is there a workaround? For CastContext i can check the play services, but app fails for the mini controller and cast buttons in the layout. How can i solve that?
