### ISSUE TITLE
Crash while launching the app

### ISSUE THREAD

**Issue by Tech-Giant** [googlesamples/android-UniversalMusicPlayer#96]
This is the stack trace :

FATAL EXCEPTION: main
                                                                          Process: com.example.android.uamp, PID: 17957
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.uamp/com.example.android.uamp.ui.MusicPlayerActivity}: java.lang.RuntimeException: com.google.android.gms.internal.zzsb$zza: No acceptable module found. Local version is 0 and remote version is 0.
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                           Caused by: java.lang.RuntimeException: com.google.android.gms.internal.zzsb$zza: No acceptable module found. Local version is 0 and remote version is 0.
                                                                              at com.google.android.gms.internal.zzni.zzbg(Unknown Source)
                                                                              at com.google.android.gms.internal.zzni.zza(Unknown Source)
                                                                              at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source)
                                                                              at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source)
                                                                              at com.example.android.uamp.ui.ActionBarCastActivity.onCreate(ActionBarCastActivity.java:141)
                                                                              at com.example.android.uamp.ui.BaseActivity.onCreate(BaseActivity.java:49)
                                                                              at com.example.android.uamp.ui.MusicPlayerActivity.onCreate(MusicPlayerActivity.java:57)
                                                                              at android.app.Activity.performCreate(Activity.java:6237)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                           Caused by: com.google.android.gms.internal.zzsb$zza: No acceptable module found. Local version is 0 and remote version is 0.
                                                                              at com.google.android.gms.internal.zzsb.zza(Unknown Source)
                                                                              at com.google.android.gms.internal.zzni.zzbg(Unknown Source) 
                                                                              at com.google.android.gms.internal.zzni.zza(Unknown Source) 
                                                                              at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source) 
                                                                              at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source) 
                                                                              at com.example.android.uamp.ui.ActionBarCastActivity.onCreate(ActionBarCastActivity.java:141) 
                                                                              at com.example.android.uamp.ui.BaseActivity.onCreate(BaseActivity.java:49) 
                                                                              at com.example.android.uamp.ui.MusicPlayerActivity.onCreate(MusicPlayerActivity.java:57) 
                                                                              at android.app.Activity.performCreate(Activity.java:6237) 
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by smishra2** [comment]
Make sure you have the latest version of Google Play Services installed on the device. https://github.com/googlesamples/android-UniversalMusicPlayer/issues/94

**Comment by ralphhm** [comment]
Same problem (exception) here with an x86 Android TV emulator API level 23 that has Google Play Services 9.4.52 and an x86 Android TV emulator API level 24 having GPS 9.3.78.

**Comment by angularzues** [comment]
Is there another way? And why I must have the latest version of Google Play Service installed?

**Comment by o0yangyang0o** [comment]
If I use ths ADV,Can I install the Google Play Service ? Does it mean I should use real cellphone to test ?

**Comment by prattpratt** [comment]
Anyways, the app should show explanation dialog why it can not continue instead of crashing.

**Comment by nic0lette** [comment]
The latest version checks if Google Play Services are available (and up to date) before attempting to setup Cast, so this should no longer happen.
