### ISSUE TITLE
 No acceptable module found. Local version is 0 and remote version is 0.

### ISSUE THREAD

**Issue by dangmeng** [googlesamples/android-UniversalMusicPlayer#97]
I try my best to run the app.By cause told me about this information: No acceptable module found. Local version is 0 and remote version is 0.

**Comment by wanyt** [comment]
我手机上安装Google Play Services和Goolge Play之后就不报异常了，

**Comment by dangmeng** [comment]
谢谢你,我试试

**Comment by littleViolence** [comment]
我安装了了呀,还是闪退

**Comment by dangmeng** [comment]
我也装了,没用 我用模拟机和真机都试过

**Comment by dangmeng** [comment]
我也装了,没用 我用模拟机和真机都试过

**Comment by littleViolence** [comment]
对呀,就不是这个原因吧

**Comment by littleViolence** [comment]
I have the same situation ,how to resolve it?

**Comment by littleViolence** [comment]
Caused by: com.google.android.gms.internal.zzsb$zza: No acceptable module found. Local version is 0 and remote version is 0.
                                                     at com.google.android.gms.internal.zzsb.zza(Unknown Source)
                                                     at com.google.android.gms.internal.zzni.zzbg(Unknown Source) 
                                                     at com.google.android.gms.internal.zzni.zza(Unknown Source) 
                                                     at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source) 
                                                     at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source) 
                                                     at com.example.android.uamp.ui.ActionBarCastActivity.onCreate(ActionBarCastActivity.java:141) 
                                                     at com.example.android.uamp.ui.BaseActivity.onCreate(BaseActivity.java:49) 
                                                     at com.example.android.uamp.ui.MusicPlayerActivity.onCreate(MusicPlayerActivity.java:57) 
                                                     at android.app.Activity.performCreate(Activity.java:6237) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by littleViolence** [comment]
online waiting for the answer

**Comment by littleViolence** [comment]
is there anyone?

**Comment by wanyt** [comment]
你运行了Google Play Service和Google Play没有，并且保证这两个应用能够正常返回数据，需要翻墙的

**Comment by littleViolence** [comment]
运行了,开了Lantern翻墙,不好用啊

**Comment by littleViolence** [comment]
始终是无法登录,估计用不了了

**Comment by zhangxincheng** [comment]
同样问题 无法解决

**Comment by luohong** [comment]
@littleViolence 我用的是nexus，开了lantern翻墙，还是运行报这个错误

**Comment by Nilpo** [comment]
Anyone? Same issue.

**Comment by LoveqLRC** [comment]
Anyone? Same issue.

**Comment by AreJay-Smith** [comment]
Same issue here.

**Comment by Huey94** [comment]
i don't have that issue

**Comment by AreJay-Smith** [comment]
Found a solution that worked for me. It's because either your device or emulator has an out-dated version of Google Play services. Right above your error you should see something in the log cat that says

Google Play services out of date. Requires 3264100 but found 3225132

Just update the Google Play services and it'll work.

**Comment by Huey94** [comment]
AreJay that makes alot of sense

**Comment by Nilpo** [comment]
I can confirm that updating Google Play Services also worked for me. This works best when using a real Google account in your emulator.

**Comment by dangmeng** [comment]
@Nilpo thank you very much smiley:

**Comment by TuYaxiong** [comment]
I have the same issue

**Comment by TestSmirk** [comment]
安装 google play  然后 墙外就可以了.,,

**Comment by sshhsun-code** [comment]
在手机上编译好这个音乐项目后，打开会闪退，找了解决办法好久都没方法
我的手机是魅族手机，在魅族的应用市场中搜索“谷歌安装器魅族专用"后，将相关的服务安装好，同时手机翻墙，再打开这个app就不会闪退了，至于具体的代码原因，目前还没有看源码，等看完源码后来再继续补充。。。。。。

**Comment by prattpratt** [comment]
This is bad practice that app just crashes instead of showing dialog with explanation and then close up without crashing.

**Comment by Nilpo** [comment]
@prattpratt It's not meant to be a production-ready application. It's an example application. You should implement your own debugging and make it your own!

**Comment by prattpratt** [comment]
@Nilpo ok, thanks. Probably you're right since it's an example app :)

**Comment by joe564338** [comment]
Its 2017 I am getting this issue on pixel phone with google play services 11.5.17. But the app has no problems on an lgd415 running lollipop and an older version of google play services.... What the heck.
10-06 21:59:38.976 6521-6895/com.zero5.com.zero5mobile E/GoogleCertificates: Failed to load com.google.android.gms.googlecertificates
                                                                             qw: No acceptable module found. Local version is 0 and remote version is 0.
                                                                                 at com.google.android.gms.dynamite.DynamiteModule.a(:com.google.android.gms.DynamiteModulesB:11)
                                                                                 at it.a(:com.google.android.gms.DynamiteModulesB:12)
                                                                                 at it.a(:com.google.android.gms.DynamiteModulesB:31)
                                                                                 at it.b(:com.google.android.gms.DynamiteModulesB:30)
                                                                                 at je.a(:com.google.android.gms.DynamiteModulesB:33)
                                                                                 at je.a(:com.google.android.gms.DynamiteModulesB:18)
                                                                                 at com.google.maps.api.android.lib6.impl.fd.a(:com.google.android.gms.DynamiteModulesB:172)
                                                                                 at com.google.maps.api.android.lib6.impl.ew.run(:com.google.android.gms.DynamiteModulesB:28)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                 at java.lang.Thread.run(Thread.java:761)
This is my own app I am making not the example app...

**Comment by jydi** [comment]
getting this problem from a code that worked in another program flawlessly

**Comment by agueroveraalvaro** [comment]
I have this problem with a `J2 Samsung 2018 8.1 API` , I don't know how to update playstore app, I have tried many methods, some help? Thanks

**Comment by CoolMind** [comment]
@agueroveraalvaro, probably you should install another firmware (that includes PlayServices, PlayMarket). Or try to install them manually.

**Comment by Krops** [comment]
I have this issue on Android TV (29 api) but don't have it on "Android for smartphone". Is there some way to add/compile module to app.

**Comment by IT-huazai** [comment]
华为手机安装Gspace + 翻墙后，依然闪退，但将应用克隆到Gspace里面后可以打开了
